# This is required for Continuous Integration for Autoware using the simulator
# and remote update (Over The Air update) to real cars.
# If you have any additional questions, please contact us at #tier4-dev channel.

services:
  autoware:
    type: roslaunch
    package_name: autoware_launch
    file_name: autoware.launch.xml
  planning_simulator:
    type: roslaunch
    package_name: integration_launch
    file_name: ci_planning_simulator.launch.xml
  planning_simulator_v2:
    type: roslaunch
    package_name: scenario_test_runner
    file_name: autoware.launch.xml
